### PR TITLE
Complex scopes admin changes.

### PR DESCRIPTION
**Pull request by leio10**
#### :tophat: Scope of work
Admin changes proposal for complex scopes use.

#### :pushpin: Related Issues
- Related to decidim/decidim#1480
- Requested in decidim/decidim#1500

### :camera: URLs
imagen

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@oriolgual @josepjaume The styles are identical to participatory processes, right? Does it make sense to bring a new "duplicated" component here? How about renaming the rules with a more generic component name? Not sure if I'm missing something.

**Comment by leio10** [comment]
@deivid-rodriguez Yes, I've copied from there. I didn't do what you are saying to avoid touching in more places than needed, but I can perfectly do if you agree. Also, there is a `_process-header.scss` file that has only two styles definition, and one is unused; I could rename it to `_full_title.scss` or similar, and move all definitions used by scopes and processes to show the page main title at full width.

PS: I've removed a `z-index: -1` from the `process-title-content` class to allow clicking on the links inside the full-width title. That breaks the design just a little bit, adding an extra border below the title. I'd leave it that way, because fixing it require too much work. But maybe you have a better solution to the problem, as placing the scope breadcrumbs out of the title.

**Comment by deivid-rodriguez** [comment]
Sounds like a plan to me :+1:, but I suggest we wait for input from the others since we might be missing something...

They way I understand this repo is to to review, approve & maintain the design components used in the main site. But I don't think we need to keep here components that use the exact same design.

**Comment by josepjaume** [comment]
@htmlboy care to chime in?

**Comment by htmlboy** [comment]
As I recall, the z-index: -1 purpose was to make an overlapping style between the process title and the sidebar. Therefore, changing this might affect some other views. Could you please provide the staging url so I can double-check it?

**Comment by leio10** [comment]
@htmlboy yes, that's true, I've commented that in my previous comment. I haven't found a way to keep that effect and allow to click links on the title. You can see the "problem" in the PR snapshot, is the shadow below the title in the left part. It also affects the processes zone in the same way. I can fix that view, since it does not have links, but I don't think that is a good idea.

Regarding staging url, I don't know if you are referring to the demo app (https://decidim-design-admin.herokuapp.com/). Sadly, it is not working right now.

So, I can think three possible solutions to this:
- Don't allow links in the title. I could put only the scope name in the title, and move breadcrumbs to other page zone. Any suggestion for the breadcrumbs placement would be very well received. :smiley:
- Refactor HTML to define a full width title div over menu and content zones without absolute positioning. I think that with these changes I could apply some CSS to hide the left part of the shadow without blocking clicks on the title.  
- Leave it as is now.  

What do you think?

**Comment by htmlboy** [comment]
@leio10 OK, I checked out your branch to better understand the problem.

The title area is not intended for breadcrumbs or complex navigation; actually, the whole navigation system relies on just 3 levels of navigation to keep it usable and not too complex.

The first level of navigation is the main-nav; the second level of navigation is the secondary-nav; and the third level of navigation is the secondary-nav subnav, as you can see in /component-meetings.

Of course you can go to deeper levels than that, but the design solved it with just text instead of links. You can see an example of this in /processes-new-2, where the title (process-title-summary) is "New process - Phases", or in /processes-new-3-add

This no-linked breadcrumb can work as well on card titles.

Of course, if this is not enough for the complex scopes, you could add links to the title summary or card title and make a full breadcrumb out of it instead of creating a new one.

Thoughts?

**Comment by leio10** [comment]
@htmlboy Ok, I think that works better and is simpler.

imagen

But this way the navigation is counterintuitive, having the "back to scopes" link in the content area. I think we can recover the settings menu. I've tried to use the third level, but its not clear enough yet.

imagen

So, I've simplified it more and I think this way its clearer than ever.

imagen

What do you think? Can the "modify" and "add" button be in the same zone? I can upload the changes if you need to test it.

**Comment by htmlboy** [comment]
Yes, actually "Modify" and "Browse" shouldn't be in the subnav (they're not real navigation, but actions). The subnav should hold the links to the main scopes, i.e.:

Scopes
--Barcelona
 --Madrid
 --Alabama

Apart from this, the last screenshot looks good, although I'd keep the " - " instead of " > " for consistency.

**Comment by leio10** [comment]
@htmlboy Ok, I've uploaded all my changes, including the " - " change. Regarding showing the main scopes in the subnav, I'm not really sure that is a good idea, your organization could have dozens or even hundreds of top level scopes...

**Comment by htmlboy** [comment]
@leio10 Sorry for the late answer. Yes, in that particular case, I wouldn't display them in the side bar but in a content list.

**Comment by josepjaume** [comment]
Nice! Merging this in.

**Pull request merged**
