### PR TITLE
Upgrade middleman to v4

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
#### :tophat: Scope of work

While investigating/fixing #18, I ended up upgrading `middleman` to v4...

This depends on #18 being merged first. It's already rebased on top of it, so you could review everything in this PR if you wanted to. I preferred to open 2 separate PR's to keep things focused.

#### :pushpin: Related Issues
- Related to #18.

#### :clipboard: Subtasks
_None_

### :camera: URLs
_None_

#### :ghost: GIF (optional)
angela

### CODE REVIEW

**Comment by oriolgual** [comment]
@deivid-rodriguez could you please use a different GIF for the PR? It doesn't seem to be very inclusive and although we don't have a [CoC](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/) yet we should try to do our best 🙂

**Comment by deivid-rodriguez** [comment]
I'm sorry, shall I change the one in #18 too? They're both part of the same joke trying to satirize (and condemn) the attitude of some man towards feminism. Apparently it wasn't understood (or you are aiming to some CoC I'm not sure I like...). Let me know and I'll change it/them.

**Comment by oriolgual** [comment]
Maybe yes? I didn't get the joke, sorry about that (I understood it the other way, but maybe I was lacking context!) The CoC it's actually related to the new feature added by GitHub and it's fairly standard.

**Review by oriolgual — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
No, my bad, gifs should be "self-contained" to avoid misunderstandings. I thought this could be an exception since one PR was building on top of the other. But I was wrong... :) I'll change both gifs as soon as possible!

**Comment by deivid-rodriguez** [comment]
GIFs have been updated! :wink:

**Review by josepjaume — APPROVED** [review]

**Pull request merged**
